check for token at beginning of workflow

diff --git a/.github/actions/set-token/action.yaml b/.github/actions/set-token/action.yaml
--- a/.github/actions/set-token/action.yaml
+++ b/.github/actions/set-token/action.yaml
@@ -14,11 +14,21 @@ runs:
   using: composite
   steps:
 
+    - name: check token
+      shell: bash
+      id: check-token
+      run: |
+        # set-token/check-token
+        if [ -z "${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}" -a -z "${{ secrets.TERRAFORM_PRIVATE_KEY }}" ] ; then
+          echo "::error ::It seems like you have no valid token."
+          exit 1
+        fi
+
     - name: set token parameters
       shell: bash
       id: set-token-parameters
       run: |
-        # set-environment/set-token/set-token-parameters
+        # set-token/set-token-parameters
         cat << EOF >> $GITHUB_ENV
         GITHUB_TOKEN=${{ inputs.github_token }}
         PERSONAL_ACCESS_TOKEN=${{ inputs.personal_access_token }}
@@ -41,7 +51,7 @@ runs:
       id: set-token
       shell: bash
       run: |
-        # set-environment/set-token/set-token
+        # set-token/set-token
 
         type="Github App Token" # so far
         token="${{ steps.create-github-app-token.outputs.token }}"
